services:
  mariadb:
    image: mariadb:lts-ubi10
    container_name: mariadb
    env_file:
      - .env
    networks:
      - matcha
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: nginx
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80

networks:
  matcha:
    driver: bridge
