services:
  mariadb:
    image: mariadb
    build: srcs/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - matcha
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mariadb_volume:/var/lib/mysql/
    ports:
      - 3001:3306

  backend:
    image: backend
    build: srcs/backend
    container_name: backend
    env_file:
      - .env
    networks:
      - matcha
    ports:
      - 3000:3000

  frontend:
    image: frontend
    build: srcs/frontend
    container_name: frontend
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - frontend_volume:/usr/share/nginx/html
    ports:
      - 8080:80

networks:
  matcha:
    driver: bridge

volumes:
  frontend_volume:
  mariadb_volume:
