services:
  mariadb:
    image: mariadb:lts-ubi10
    container_name: mariadb
    env_file:
      - .env
    networks:
      - matcha
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_volume:/var/lib/mysql/
      - ./srcs/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - 8888:3306

  nginx:
    image: nginx:alpine
    container_name: nginx
    env_file:
      - .env
    networks:
      - matcha
    volumes:
      - frontend_volume:/usr/share/nginx/html
    ports:
      - 8080:80

networks:
  matcha:
    driver: bridge

volumes:
  frontend_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/frontend
  mariadb_volume:
    driver : local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  
